# pytorch_lightning==1.7.7
seed_everything: 0
ckpt_path: null
model:
  class_path: design.huggingface.LitModel
  init_args:
    num_users: 52205
    num_items: 57289
    max_freq: 539
    mask_token: 57290
    max_position: 50
    model_type: 'bert'
    # change above
    pad_token: 0
    hidden_size: 50
    num_attention_heads: 1
    dropout_prob: 0.5
    loss_type: 'ce'
    task_type: 'ar'
    num_hidden_layers: 2
    optimizer_type: adam
    lr: 0.001
    weight_decay: 0
    eval_neg: 0
data:
  class_path: design.huggingface.LitData
  init_args:
    data_dir: 'your_ModSAR_dir/data/modularized/Beauty'
    batch_size: 128
    mask_prob: 0.8
    item_sse_prob: 0
    user_sse_prob: 0
trainer:
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: ./output_lightning
      name: csv_logs
      
  enable_checkpointing: true
  callbacks:
    class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      save_top_k: 1
      monitor: valid/Recall@10
      mode: max
      every_n_epochs: 5
    # class_path: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    # init_args:
    #   patience: 10
    #   monitor: valid/Recall@10
    #   verbose: false
    #   mode: max
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: [0]
  accelerator: 'gpu'
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 5
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 200
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  # weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: True
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  # amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle